In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("../data/Telco_customer_churn.xlsx")

In [5]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [6]:
df.tail()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 2.9+ MB

In [8]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [9]:
df.isnull().sum().sum()

np.int64(5174)

In [10]:
df.shape

(7043, 33)

In [11]:
df.sample(6)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
5009,9054-FOWNV,1,United States,California,Brentwood,94513,"37.908242, -121.682472",37.908242,-121.682472,Male,...,Month-to-month,Yes,Electronic check,88.75,1885.15,No,0,48,5585,NaN
3319,4445-KWOKW,1,United States,California,Potrero,91963,"32.619465, -116.593605",32.619465,-116.593605,Female,...,One year,Yes,Bank transfer (automatic),60.15,2421.6,No,0,55,5988,NaN
3234,7369-TRPFD,1,United States,California,Chatsworth,91311,"34.294142, -118.603883",34.294142,-118.603883,Male,...,One year,No,Mailed check,18.80,279.2,No,0,43,2916,NaN
6330,0613-WUXUM,1,United States,California,Soquel,95073,"37.023669, -121.946461",37.023669,-121.946461,Female,...,Two year,Yes,Mailed check,19.20,1401.4,No,0,53,5261,NaN
1026,3886-CERTZ,1,United States,California,Fullerton,92831,"33.879983, -117.895482",33.879983,-117.895482,Female,...,One year,Yes,Electronic check,109.25,8109.8,Yes,1,97,4261,Attitude of service provider
686,6769-DCQLI,1,United States,California,Pope Valley,94567,"38.672708, -122.403219",38.672708,-122.403219,Male,...,One year,Yes,Bank transfer (automatic),105.00,5426.85,Yes,1,85,4630,Don't know

In [ ]:
columns = ['Country',
 'State',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'Churn Reason']

for col in columns:
    print(f"\nUnique value in {col}: {df[col].unique().tolist()}")

In [12]:
df['Dependents'].value_counts()

Dependents
No     5416
Yes    1627
Name: count, dtype: int64

In [13]:
print(df['Churn Score'].max())
print(df['Churn Score'].min())
print(df['Churn Score'].mean())

100
5
58.69941786170666

In [14]:
df['Streaming Movies'].value_counts()

Streaming Movies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [15]:
print(df.duplicated().sum())

0

In [16]:
for cols in df.columns:
    print(f"{cols}: {df[cols].nunique()}")

CustomerID: 7043
Count: 1
Country: 1
State: 1
City: 1129
Zip Code: 1652
Lat Long: 1652
Latitude: 1652
Longitude: 1651
Gender: 2
Senior Citizen: 2
Partner: 2
Dependents: 2
Tenure Months: 73
Phone Service: 2
Multiple Lines: 3
Internet Service: 3
Online Security: 3
Online Backup: 3
Device Protection: 3
Tech Support: 3
Streaming TV: 3
Streaming Movies: 3
Contract: 3
Paperless Billing: 2
Payment Method: 4
Monthly Charges: 1585
Total Charges: 6531
Churn Label: 2
Churn Value: 2
Churn Score: 85
CLTV: 3438
Churn Reason: 20

In [17]:
display(df['Churn Value'].value_counts())

display(df['Churn Label'].value_counts())

Churn Value
0    5174
1    1869
Name: count, dtype: int64

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [18]:
df.dtypes

CustomerID               str
Count                  int64
Country                  str
State                    str
City                     str
Zip Code               int64
Lat Long                 str
Latitude             float64
Longitude            float64
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges         object
Churn Label              str
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason             str
dtype: object

In [19]:
df[df['Total Charges'].str.strip() == '']

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [20]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Charges'].dtype
print(df['Total Charges'].isna().sum())
df[df['Total Charges'].isna()][['Tenure Months', 'Monthly Charges', 'Churn Label']]
df.dropna(subset=['Total Charges'], inplace=True)
print(df['Total Charges'].isna().sum())

11
0

In [21]:
df.groupby('Churn Label')['Churn Reason'].apply(lambda x: x.isna().sum())

Churn Label
No     5163
Yes       0
Name: Churn Reason, dtype: int64

In [22]:
text_cols = df.select_dtypes(include= str).columns.tolist()
for text in text_cols:
    df[text] = df[text].str.strip().str.title()
    print(f"'{text}' column handled")

'CustomerID' column handled
'Country' column handled
'State' column handled
'City' column handled
'Lat Long' column handled
'Gender' column handled
'Senior Citizen' column handled
'Partner' column handled
'Dependents' column handled
'Phone Service' column handled
'Multiple Lines' column handled
'Internet Service' column handled
'Online Security' column handled
'Online Backup' column handled
'Device Protection' column handled
'Tech Support' column handled
'Streaming TV' column handled
'Streaming Movies' column handled
'Contract' column handled
'Paperless Billing' column handled
'Payment Method' column handled
'Churn Label' column handled
'Churn Reason' column handled

In [23]:
print(df.loc[df['Churn Value'] > 1].count)
print(df.loc[df['Churn Value'] < 0].count)

<bound method DataFrame.count of Empty DataFrame
Columns: [CustomerID, Count, Country, State, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Internet Service, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Payment Method, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason]
Index: []

[0 rows x 33 columns]>
<bound method DataFrame.count of Empty DataFrame
Columns: [CustomerID, Count, Country, State, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Internet Service, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Payment Method, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason]
Index: []

[0 rows x 33 columns]>

In [24]:
num_cols = ['Tenure Months', 'Monthly Charges', 'Churn Value', 'Churn Score', 'CLTV']

for col in num_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"\n→ Found {len(outliers)} outliers in {col}")

→ Found 0 outliers in Tenure Months

→ Found 0 outliers in Monthly Charges

→ Found 0 outliers in Churn Value

→ Found 0 outliers in Churn Score

→ Found 0 outliers in CLTV

In [25]:
print("\n",df['Count'].unique())
print("\n",df['Country'].unique())
print("\n",df['State'].unique())

 [1]

 <ArrowStringArray>
['United States']
Length: 1, dtype: str

 <ArrowStringArray>
['California']
Length: 1, dtype: str

### 🎉 Data Examination and Cleaning completed!

In [26]:
df.columns.to_list()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [27]:
output_file = "data_cleaned.xlsx"
df.to_excel(output_file, index=False)

print("Cleaned dataset saved as:", output_file)

Cleaned dataset saved as: data_cleaned.xlsx